##########################################################
# application.yaml   (used for development purposes)
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080

es.url: http://localhost:9201

# SET ACTIVE PROFILE HERE
spring.profiles.active: test

  ###########################################################
  # Database Settings
  ##########################################################
app.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/app1_db
  username: app1_user
  password: ENC(UMGziawNgizYtbWgBI0JUA==)
  maxPoolSize: 10

development.mode: false
#network.name: NIPR

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: 'ab5823423464j1k2#><!!6298<-+'

---
# Dev Profile
spring:
  profiles: dev
network.name: NIPR
hdfs.enable: false
show.classified.banner: false
---
# Test Profile
spring:
  profiles: test
network.name: SIPR
hdfs.enable: true
show.classified.banner: true
---