##########################################################
# application.yaml   (used for development purposes)
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080

  ###########################################################
  # Database Settings
  ##########################################################
app.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/app1_db
  username: app1_user
  password: ENC(UMGziawNgizYtbWgBI0JUA==)
  maxPoolSize: 10

development.mode: FaLsE
network.name: SIPR

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: 'ab5823423464j1k2#><!!6298<-+'